from django.db import models
class User(models.Model):
	username=models.CharField(max_length=256)
	password=models.CharField(max_length=256)
	def __str__(self):
		return self.username
class Table(models.Model):
	name=models.CharField(max_length=512,null=True,blank=True)
	day_before=models.CharField(max_length=512,null=True,blank=True)	
	operate1=models.CharField(max_length=512,null=True,blank=True)
	operate2=models.CharField(max_length=512,null=True,blank=True)
	operate3=models.CharField(max_length=512,null=True,blank=True)
	operate4=models.CharField(max_length=512,null=True,blank=True)
	operate5=models.CharField(max_length=512,null=True,blank=True)
	operate6=models.CharField(max_length=512,null=True,blank=True)
	operate7=models.CharField(max_length=512,null=True,blank=True)
	operate8=models.CharField(max_length=512,null=True,blank=True)
	operate9=models.CharField(max_length=512,null=True,blank=True)
	operate10=models.CharField(max_length=512,null=True,blank=True)
	operate11=models.CharField(max_length=512,null=True,blank=True)
	operate12=models.CharField(max_length=512,null=True,blank=True)
	operate13=models.CharField(max_length=512,null=True,blank=True)
	operate14=models.CharField(max_length=512,null=True,blank=True)
	operate15=models.CharField(max_length=512,null=True,blank=True)
	operate16=models.CharField(max_length=512,null=True,blank=True)
	operate17=models.CharField(max_length=512,null=True,blank=True)
	operate18=models.CharField(max_length=512,null=True,blank=True)
	operate19=models.CharField(max_length=512,null=True,blank=True)
	operate20=models.CharField(max_length=512,null=True,blank=True)
	operate21=models.CharField(max_length=512,null=True,blank=True)
	operate22=models.CharField(max_length=512,null=True,blank=True)
	operate23=models.CharField(max_length=512,null=True,blank=True)
	operate24=models.CharField(max_length=512,null=True,blank=True)
	operate25=models.CharField(max_length=512,null=True,blank=True)
	operate26=models.CharField(max_length=512,null=True,blank=True)
	operate27=models.CharField(max_length=512,null=True,blank=True)
	operate28=models.CharField(max_length=512,null=True,blank=True)
	operate29=models.CharField(max_length=512,null=True,blank=True)
	operate30=models.CharField(max_length=512,null=True,blank=True)
	operate31=models.CharField(max_length=512,null=True,blank=True)
	operate32=models.CharField(max_length=512,null=True,blank=True)
	operate33=models.CharField(max_length=512,null=True,blank=True)
	operate34=models.CharField(max_length=512,null=True,blank=True)
	operate35=models.CharField(max_length=512,null=True,blank=True)
	operate36=models.CharField(max_length=512,null=True,blank=True)
	operate37=models.CharField(max_length=512,null=True,blank=True)
	operate38=models.CharField(max_length=512,null=True,blank=True)
	operate39=models.CharField(max_length=512,null=True,blank=True)
	operate40=models.CharField(max_length=512,null=True,blank=True)
	def __str__(self):
		return self.name