# Generated by Django 2.0.7 on 2018-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('day_before', models.CharField(blank=True, max_length=512, null=True)),
                ('operate1', models.CharField(blank=True, max_length=512, null=True)),
                ('operate2', models.CharField(blank=True, max_length=512, null=True)),
                ('operate3', models.CharField(blank=True, max_length=512, null=True)),
                ('operate4', models.CharField(blank=True, max_length=512, null=True)),
                ('operate5', models.CharField(blank=True, max_length=512, null=True)),
                ('operate6', models.CharField(blank=True, max_length=512, null=True)),
                ('operate7', models.CharField(blank=True, max_length=512, null=True)),
                ('operate8', models.CharField(blank=True, max_length=512, null=True)),
                ('operate9', models.CharField(blank=True, max_length=512, null=True)),
                ('operate10', models.CharField(blank=True, max_length=512, null=True)),
                ('operate11', models.CharField(blank=True, max_length=512, null=True)),
                ('operate12', models.CharField(blank=True, max_length=512, null=True)),
                ('operate13', models.CharField(blank=True, max_length=512, null=True)),
                ('operate14', models.CharField(blank=True, max_length=512, null=True)),
                ('operate15', models.CharField(blank=True, max_length=512, null=True)),
                ('operate16', models.CharField(blank=True, max_length=512, null=True)),
                ('operate17', models.CharField(blank=True, max_length=512, null=True)),
                ('operate18', models.CharField(blank=True, max_length=512, null=True)),
                ('operate19', models.CharField(blank=True, max_length=512, null=True)),
                ('operate20', models.CharField(blank=True, max_length=512, null=True)),
                ('operate21', models.CharField(blank=True, max_length=512, null=True)),
                ('operate22', models.CharField(blank=True, max_length=512, null=True)),
                ('operate23', models.CharField(blank=True, max_length=512, null=True)),
                ('operate24', models.CharField(blank=True, max_length=512, null=True)),
                ('operate25', models.CharField(blank=True, max_length=512, null=True)),
                ('operate26', models.CharField(blank=True, max_length=512, null=True)),
                ('operate27', models.CharField(blank=True, max_length=512, null=True)),
                ('operate28', models.CharField(blank=True, max_length=512, null=True)),
                ('operate29', models.CharField(blank=True, max_length=512, null=True)),
                ('operate30', models.CharField(blank=True, max_length=512, null=True)),
                ('operate31', models.CharField(blank=True, max_length=512, null=True)),
                ('operate32', models.CharField(blank=True, max_length=512, null=True)),
                ('operate33', models.CharField(blank=True, max_length=512, null=True)),
                ('operate34', models.CharField(blank=True, max_length=512, null=True)),
                ('operate35', models.CharField(blank=True, max_length=512, null=True)),
                ('operate36', models.CharField(blank=True, max_length=512, null=True)),
                ('operate37', models.CharField(blank=True, max_length=512, null=True)),
                ('operate38', models.CharField(blank=True, max_length=512, null=True)),
                ('operate39', models.CharField(blank=True, max_length=512, null=True)),
                ('operate40', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
